name: Rust

on:
  push:
    branches: 
      - '*'
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set coorect permissions
      run: chmod +x ./latest_dir.sh 
    - name: Go to newest folder
      run: ./latest_dir.sh 
    - name: Build
      run: cargo build --verbose
    - name: Run program
      run: cargo run
    - name: Run tests
      run: cargo test --verbose
