name: Rust

on:
  push:
    branches: 
      - main

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set coorect permissions
      run: chmod +x ./latest_dir.sh 
    - name: Go to newest folder and build
      run: | 
        ./latest_dir.sh 
